import avatar from './image/avatar1.png';
import avatar1 from './image/avatar4.jpg';
export const userData = [
    {
      name: 'Jan',
      "Active User": 4000,
    },
    {
      name: 'Feb',
      "Active User": 3000,
    },
    {
      name: 'Mar',
      "Active User": 2000,
    },
    {
      name: 'Apr',
      "Active User": 2780,
    },
    {
      name: 'May',
      "Active User": 1890,
    },
    {
      name: 'Jun',
      "Active User": 2390,
    },
    {
      name: 'July',
      "Active User": 3490,
    },
    {
      name: 'Aug',
      "Active User": 2000,
    },
    {
      name: 'Sept',
      "Active User": 2780,
    },
    {
      name: 'Oct',
      "Active User": 1890,
    },
    {
      name: 'Nov',
      "Active User": 2390,
    },
    {
      name: 'Dec',
      "Active User": 3490,
    },
  ];
export const productData = [
    {
      name: 'Jan',
      "Sales": 3000,
    },
    {
      name: 'Feb',
      "Sales": 2000,
    },
    {
      name: 'Mar',
      "Sales": 3000,
    },
    
  ];

  export const userRows = [
    { id: 1, username: ' Jon Snow', 
        avatar: avatar,
        email:'jon@gmail.com',
        status:'active',
        Transaction:'$120.00',
    },
    { id: 2, username: ' Jon Snow', 
        avatar: avatar,
        email:'jon@gmail.com',
        status:'active',
        Transaction:'$120.00',
    },
    { id: 3, username: ' Jon Snow', 
        avatar: avatar,
        email:'jon@gmail.com',
        status:'active',
        Transaction:'$120.00',
    },
    { id: 4, username: ' Jon Snow', 
        avatar: avatar,
        email:'jon@gmail.com',
        status:'active',
        Transaction:'$120.00',
    },
    { id: 5, username: ' Jon Snow', 
        avatar: avatar,
        email:'jon@gmail.com',
        status:'active',
        Transaction:'$120.00',
    },
    { id: 6, username: ' Jon Snow', 
        avatar: avatar,
        email:'jon@gmail.com',
        status:'active',
        Transaction:'$120.00',
    },
    { id: 7, username: ' Jon Snow', 
        avatar: avatar,
        email:'jon@gmail.com',
        status:'active',
        Transaction:'$120.00',
    },
    { id: 8, username: ' Jon Snow', 
        avatar: avatar,
        email:'jon@gmail.com',
        status:'active',
        Transaction:'$120.00',
    },
    { id: 9, username: ' Jon Snow', 
        avatar: avatar,
        email:'jon@gmail.com',
        status:'active',
        Transaction:'$120.00',
    },
    { id: 10, username: ' Jon Snow', 
        avatar: avatar,
        email:'jon@gmail.com',
        status:'active',
        Transaction:'$120.00',
    },
  ];
  export const productRows = [
    { id: 1, name: ' Apple Airpods', 
        avatar: avatar1,
        stock:'123',
        status:'active',
        price:'$120.00',
    },
    { id: 2, name: ' Apple Airpods', 
        avatar: avatar1,
        stock:'123',
        status:'active',
        price:'$120.00',
    },
    { id: 3, name: ' Apple Airpods', 
        avatar: avatar1,
        stock:'123',
        status:'active',
        price:'$120.00',
    },
    { id: 4, name: ' Apple Airpods', 
        avatar: avatar1,
        stock:'123',
        status:'active',
        price:'$120.00',
    },
    { id: 5, name: ' Apple Airpods', 
        avatar: avatar1,
        stock:'123',
        status:'active',
        price:'$120.00',
    },
    { id: 6, name: ' Apple Airpods', 
        avatar: avatar1,
        stock:'123',
        status:'active',
        price:'$120.00',
    },
    { id: 7, name: ' Apple Airpods', 
        avatar: avatar1,
        stock:'123',
        status:'active',
        price:'$120.00',
    },
    { id: 8, name: ' Apple Airpods', 
        avatar: avatar1,
        stock:'123',
        status:'active',
        price:'$120.00',
    },
    { id: 9, name: ' Apple Airpods', 
        avatar: avatar1,
        stock:'123',
        status:'active',
        price:'$120.00',
    },
    { id: 10, name: ' Apple Airpods', 
        avatar: avatar1,
        stock:'123',
        status:'active',
        price:'$120.00',
    },
  ];